install.packages("naivebayes")
install.packages("ggplots")
install.packages("caret")
install.packages("ggplot2")
install.packages("e1071")
library(ggplot2)
library(caret)
library(e1071)
Salary_test <- read_csv("D:/ExcelR/assingments/Naive Baye's/SalaryData_Train.csv")
View(Salary_test)
str(Salary_test)
attach(Salary_test)
class(Salary_test)
Salary_test$workclass <- as.factor(Salary_test$workclass)
Salary_test$education <- as.factor(Salary_test$education)
Salary_test$maritalstatus <- as.factor(Salary_test$maritalstatus)
Salary_test$occupation <- as.factor(Salary_test$occupation)
Salary_test$relationship <- as.factor(Salary_test$relationship)
Salary_test$race <- as.factor(Salary_test$race)
Salary_test$sex <- as.factor(Salary_test$sex)
Salary_test$native <- as.factor(Salary_test$native)
Salary_test$Salary <- as.factor(Salary_test$Salary)
Salary_test$educationno <- as.factor(Salary_test$educationno)


attach(Salary_test)
str(Salary_test)
Salary_test$workclass <- as.factor(Salary_test$workclass)
Salary_test$education <- as.factor(Salary_test$education)
Salary_test$maritalstatus <- as.factor(Salary_test$maritalstatus)
Salary_test$occupation <- as.factor(Salary_test$occupation)
Salary_test$relationship <- as.factor(Salary_test$relationship)
Salary_test$race <- as.factor(Salary_test$race)
Salary_test$sex <- as.factor(Salary_test$sex)
Salary_test$native <- as.factor(Salary_test$native)
Salary_test$Salary <- as.factor(Salary_test$Salary)
Salary_test$educationno <- as.factor(Salary_test$educationno)

Model <- naiveBayes(Salary_Train$Salary ~ ., data = Salary_Train)
Model
Model_pred <- predict(Model,Salary_test)

mean(Model_pred==Salary_test$Salary)

confusionMatrix(Model_pred,Salary_test$Salary)
